@echo off

SET FILE_EXT=.xml
SET DATAFILE_LIST=xmlmysql.txt

REM IF EXIST %DATAFILE_LIST% DEL /Q %DATAFILE_LIST% > NUL

ECHO.@ECHO OFF>%TEMP%\EFGMYSQLTEMP.BAT
ECHO.SET X=%%1>>%TEMP%\EFGMYSQLTEMP.BAT
ECHO.SET Y=%%X:~0,-4%%>>%TEMP%\EFGMYSQLTEMP.BAT
ECHO.ECHO.%%Y%%,Data,Info^>^>%%2>>%TEMP%\EFGMYSQLTEMP.BAT

REM FOR %%F in (*Data.xml) DO call %TEMP%\EFGMYSQLTEMP.BAT %%~nF %CD%\%DATAFILE_LIST%

REM DEL /Q %TEMP%\EFGMYSQLTEMP.BAT > NUL

FOR /F "tokens=1-3 delims=," %%i IN (%DATAFILE_LIST%) DO call createRDB.bat %%i%%j%FILE_EXT% %%i%%k%FILE_EXT%

REM IF EXIST %DATAFILE_LIST% DEL /Q %DATAFILE_LIST% > NUL

@echo on